[package]
name = "chip-8-emulator"
version = "0.1.0"
edition = "2024"

[dependencies]
fastrand= { version = "2.3.0", features = ["js"] }
rodio = "0.20"
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"

[lib]
crate-type= ["cdylib"]